package trevo;


import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BILA
 */
public class LottoU extends javax.swing.JFrame {

    /**
     * Creates new form Lotto
     */
    public LottoU() {
        initComponents();
        btnG1.setEnabled(false);
        btnG2.setEnabled(false);
        btnG3.setEnabled(false);
        lblMul.setVisible(false);
        btnAp.setEnabled(false);
        lblSin.setVisible(false);
        lblAd.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblB1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblB2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblB3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btnG1 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtB3 = new javax.swing.JTextField();
        txtB2 = new javax.swing.JTextField();
        txtB1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnConf = new javax.swing.JButton();
        btnAp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spAp = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lblAp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblMul = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblSin = new javax.swing.JLabel();
        lblGanho = new javax.swing.JLabel();
        lblGa = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblAd = new javax.swing.JLabel();
        lblPerd = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da sorte");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Jogo da sorte");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bola 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bola 2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bola 3");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblB1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblB1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblB1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblB2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblB2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblB2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblB3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblB3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblB3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(51, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 153, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("Apostas");

        btnG1.setBackground(new java.awt.Color(51, 153, 0));
        btnG1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnG1.setForeground(new java.awt.Color(255, 255, 255));
        btnG1.setText("Girar");
        btnG1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1ActionPerformed(evt);
            }
        });

        btnG2.setBackground(new java.awt.Color(51, 153, 0));
        btnG2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnG2.setForeground(new java.awt.Color(255, 255, 255));
        btnG2.setText("Girar");
        btnG2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2ActionPerformed(evt);
            }
        });

        btnG3.setBackground(new java.awt.Color(51, 153, 0));
        btnG3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnG3.setForeground(new java.awt.Color(255, 255, 255));
        btnG3.setText("Girar");
        btnG3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bola 1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bola 2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bola 3");

        txtB3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtB2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(51, 153, 0));
        jSeparator2.setForeground(new java.awt.Color(51, 153, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(4, 8));

        jSeparator3.setBackground(new java.awt.Color(51, 153, 0));
        jSeparator3.setForeground(new java.awt.Color(51, 153, 0));

        btnConf.setBackground(new java.awt.Color(51, 153, 0));
        btnConf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConf.setForeground(new java.awt.Color(255, 255, 255));
        btnConf.setText("Confirmar");
        btnConf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfActionPerformed(evt);
            }
        });

        btnAp.setBackground(new java.awt.Color(204, 0, 0));
        btnAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAp.setForeground(new java.awt.Color(255, 255, 255));
        btnAp.setText("Apostar");
        btnAp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faça a sua aposta:");

        spAp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spAp.setModel(new javax.swing.SpinnerNumberModel(20, 20, 30000, 5));
        spAp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor da aposta:");

        lblAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAp.setForeground(new java.awt.Color(204, 0, 0));
        lblAp.setText("0.00");

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Feito por @Dev Wilson Bila");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(92, 92, 92))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Saldo disponivel :");

        lblSal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSal.setForeground(new java.awt.Color(51, 153, 0));
        lblSal.setText("1000");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("meticais");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("meticais");

        lblMul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMul.setForeground(new java.awt.Color(51, 153, 0));
        lblMul.setText("x8");

        lblSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSub.setForeground(new java.awt.Color(204, 0, 0));
        lblSub.setText("0.00");

        lblSin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSin.setForeground(new java.awt.Color(204, 0, 0));
        lblSin.setText("-");

        lblGanho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGanho.setForeground(new java.awt.Color(255, 255, 255));
        lblGanho.setText("Valor a ganhar:");

        lblGa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGa.setForeground(new java.awt.Color(51, 153, 0));
        lblGa.setText("0.00");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("meticais");

        lblAd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAd.setForeground(new java.awt.Color(51, 153, 0));
        lblAd.setText("+");

        lblPerd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPerd.setForeground(new java.awt.Color(255, 255, 255));
        lblPerd.setText("Valor a perder:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("meticais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConf)
                .addGap(38, 38, 38))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnG1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnG2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnG3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel9))
                                    .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtB2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(txtB3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblAp)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spAp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(40, 40, 40)
                                                .addComponent(lblMul))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblGanho)
                                        .addGap(4, 4, 4)
                                        .addComponent(lblAd)
                                        .addGap(4, 4, 4)
                                        .addComponent(lblGa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPerd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel19))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnG2)
                                    .addComponent(btnG3)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnG1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblSal)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(lblMul)
                    .addComponent(lblAp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGanho)
                    .addComponent(lblGa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(lblAd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerd)
                    .addComponent(jLabel19)
                    .addComponent(lblSub)
                    .addComponent(lblSin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtB2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtB3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAp)
                    .addComponent(btnConf))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfActionPerformed
        try {
        
        int ap1 = Integer.parseInt(txtB2.getText());
        int ap2 = Integer.parseInt(txtB1.getText());
        int ap3 = Integer.parseInt(txtB3.getText());
        int sal= Integer.parseInt(lblSal.getText());
        int ap = Integer.parseInt(spAp.getValue().toString());

            if (sal>=ap) { 
                
                if (ap1>=1 && ap1<=9 && ap2>=1 && ap2<=9 && ap3>=1 && ap3<=9) {
                    
                    if (ap1!=ap2 && ap1!=ap3 && ap2!=ap3) {
                        btnG1.setEnabled(true);   
                        lblAp.setText(Integer.toString(ap));
                        btnConf.setEnabled(false);
                        txtB2.setEditable(false);
                        txtB1.setEditable(false);
                        txtB3.setEditable(false);
                        spAp.setEnabled(false);
                        
                        if(ap>550){
                        int arp = Integer.parseInt(spAp.getValue().toString());
                        int nqs=arp*12;
                        lblGa.setText(Integer.toString(nqs));
                        lblSub.setText(Integer.toString(ap));
                        lblSin.setVisible(true);
                        lblAd.setVisible(true);
                        }
                        else{
                        int arp = Integer.parseInt(spAp.getValue().toString());
                        int nqs=arp*8;
                        lblGa.setText(Integer.toString(nqs));
                        lblSub.setText(Integer.toString(ap));
                        lblSin.setVisible(true);
                        lblAd.setVisible(true);
                        }
                    } 
                    else{
                       JOptionPane.showMessageDialog(this, "Não repita os números", "", JOptionPane.ERROR_MESSAGE);  
                    }
                     
                }
                else{
                    JOptionPane.showMessageDialog(this, "Números inválidos! \nDigite números no intervalo de 1 a 9", "", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            else{
            JOptionPane.showMessageDialog(this, "Saldo insuficiente!", "", JOptionPane.WARNING_MESSAGE);
            }
            if (sal<20) { 
            int option = JOptionPane.showConfirmDialog(this, "Deseja reiniciar?", "", JOptionPane.YES_NO_OPTION);
            int num=1000;
            switch(option){
                case 0: lblSal.setText(Integer.toString(num)); break;
            }
            spAp.setValue(20);
            txtB2.setText("");
            txtB1.setText("");
            txtB3.setText("");}
            
        } catch (HeadlessException | NumberFormatException erro) {
            JOptionPane.showMessageDialog( this, "Preencha devidamente!", "", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnConfActionPerformed

    private void btnG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1ActionPerformed
 
            int ale =(int) (2 + Math.random()* 9-1);
            lblB1.setText(Integer.toString(ale));
            btnG1.setEnabled(false);
            btnG2.setEnabled(true);
            spAp.setEnabled(false); 
  
    }//GEN-LAST:event_btnG1ActionPerformed

    private void btnG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2ActionPerformed

        int n2 = Integer.parseInt(lblB1.getText());
        int ale =(int) (2 + Math.random()*9-1);
       
            lblB2.setText(Integer.toString(ale));
            btnG2.setEnabled(false);
            btnG3.setEnabled(true);
            spAp.setEnabled(false);
     
        
        if (ale==n2) {
            int ale2 =(int) (2 + Math.random()*7-1);
            lblB2.setText(Integer.toString(ale2));
        } 
        
    }//GEN-LAST:event_btnG2ActionPerformed

    private void btnG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG3ActionPerformed

        int n1 = Integer.parseInt(lblB1.getText());
        int n2 = Integer.parseInt(lblB2.getText());
        
             int ale =(int) (2 + Math.random()*9-1);
            lblB3.setText(Integer.toString(ale));
            btnG3.setEnabled(false);
            spAp.setEnabled(false);
        
        if (ale==n1 || ale==n2) {
            int ale2 =(int) (2 + Math.random()*5-1);
            lblB3.setText(Integer.toString(ale2));
        }
        else{
            lblB3.setText(Integer.toString(ale));
        }
        
            int b1= Integer.parseInt(lblB1.getText());
            int b2= Integer.parseInt(lblB2.getText());
            int b3= Integer.parseInt(lblB3.getText());
            int t1= Integer.parseInt(txtB2.getText());
            int t2= Integer.parseInt(txtB1.getText());
            int t3= Integer.parseInt(txtB3.getText());
            int sal= Integer.parseInt(lblSal.getText());
            int ap = Integer.parseInt(spAp.getValue().toString());
            lblAp.setText(Integer.toString(ap));
        
        if (b1!=b2 && b1!=b3 && b2!=b3) {
                btnAp.setEnabled(true);    
            if (b1!=t1 && b1!=t2 && b1!=t3 || b2!=t1 && b2!=t2 && b2!=t3 || b3!=t1 && b3!=t2 && b3!=t3) {
                int sub= sal-ap;
                lblSal.setText(Integer.toString(sub));
                JOptionPane.showMessageDialog(this, "HOJE A SUA SORTE ESTÁ RUIM!");
                lblPerd.setText("Valor perdido:");
                lblGanho.setText("Valor ganho:");
                lblGa.setText("0.00");
                lblAd.setVisible(false);
            }
       
            else{
                if(ap>550){
                int ns=ap*12;
                JOptionPane.showMessageDialog(this, "PARABÉNS, VOCÊ GANHOU " +ns+ " METICAIS"); 
                int sub= ns+sal;
                lblSal.setText(Integer.toString(sub));
                lblMul.setVisible(true);
                lblGanho.setText("Valor ganho:");
                lblPerd.setText("Valor perdido:");
                lblSub.setText("0.00");
                lblSin.setVisible(false);
                lblMul.setText("x12");
                
                }
                else{
                int ns=ap*8;
                JOptionPane.showMessageDialog(this, "PARABÉNS, VOCÊ GANHOU " +ns+ " METICAIS"); 
                int sub= ns+sal;
                lblSal.setText(Integer.toString(sub));
                lblMul.setVisible(true);
                lblGanho.setText("Valor ganho:");
                lblPerd.setText("Valor perdido:");
                lblSub.setText("0.00");
                lblSin.setVisible(false);
                
                }
                }
            }  
        
        else{
           JOptionPane.showMessageDialog(this, "Houve um erro...\n Por favor, gire novamente!", "", JOptionPane.ERROR_MESSAGE);  
           btnG1.setEnabled(true);  
           btnAp.setEnabled(false);
                } 
            
    }//GEN-LAST:event_btnG3ActionPerformed

    private void btnApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApActionPerformed

            spAp.setValue(20);
            spAp.setEnabled(true);
            btnConf.setEnabled(true);
            txtB2.setEditable(true);
            txtB1.setEditable(true);
            txtB3.setEditable(true);
            lblMul.setVisible(false);
            lblMul.setText("x8");
            lblSub.setText("0.00");
            lblGa.setText("0.00");
            lblGanho.setText("Valor a ganhar:");
            lblPerd.setText("Valor a perder:");
            lblSin.setVisible(false);
            lblAd.setVisible(false);
            btnAp.setEnabled(false);
            
        
            txtB2.setText("");
            txtB1.setText("");
            txtB3.setText("");
        
            lblB1.setText("");
            lblB2.setText("");
            lblB3.setText("");
            lblAp.setText("0.00");
    }//GEN-LAST:event_btnApActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LottoU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAp;
    private javax.swing.JButton btnConf;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblAp;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblGa;
    private javax.swing.JLabel lblGanho;
    private javax.swing.JLabel lblMul;
    private javax.swing.JLabel lblPerd;
    private javax.swing.JLabel lblSal;
    private javax.swing.JLabel lblSin;
    private javax.swing.JLabel lblSub;
    private javax.swing.JSpinner spAp;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtB3;
    // End of variables declaration//GEN-END:variables
}
